version: '3.7'

services:
  #
  # build
  #
  openldap-build:
    build:
      context: openldap
      dockerfile: Dockerfile
      target: build
    image: takumi/openldap:build
    hostname: openldap-build
    container_name: openldap-build
    command: /bin/true
    networks:
      - simple-ldap

  #
  # service
  #
  openldap:
    build:
      context: openldap
      dockerfile: Dockerfile
      target: prod
    image: takumi/openldap:latest
    hostname: openldap
    container_name: openldap
    restart: always
    networks:
      - simple-ldap
    ports:
      - 389:389
      - 636:636
    environment:
      - "OPENLDAP_UID=${OPENLDAP_UID:-1000}"
      - "OPENLDAP_GID=${OPENLDAP_GID:-1000}"
      - "OPENLDAP_DEBUG=${OPENLDAP_DEBUG:-0}"
      - "OPENLDAP_CONFIG_ROOTDN=${OPENLDAP_CONFIG_ROOTDN:-cn=admin,cn=config}"
      - "OPENLDAP_CONFIG_ROOTPW=${OPENLDAP_CONFIG_ROOTPW:-config}"

  #
  # build
  #
  ldap-account-manager-build:
    build:
      context: ldap-account-manager
      dockerfile: Dockerfile
      target: build
    image: takumi/ldap-account-manager:build
    hostname: ldap-account-manager-build
    container_name: ldap-account-manager-build
    command: /bin/true
    networks:
      - simple-ldap

  #
  # service
  #
  ldap-account-manager:
    build:
      context: ldap-account-manager
      dockerfile: Dockerfile
      target: prod
    image: takumi/ldap-account-manager:latest
    hostname: ldap-account-manager
    container_name: ldap-account-manager
    restart: always
    networks:
      - simple-ldap
    ports:
      - 8000:80
      - 8443:443
    environment:
      - "PHP_FPM_UID=${PHP_FPM_UID:-1000}"
      - "PHP_FPM_GID=${PHP_FPM_GID:-1000}"

networks:
  simple-ldap:
